# Generated by Django 6.0.6 on 2026-06-22 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
