# Generated by Django 6.0.6 on 2026-06-22 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0002_artifact_error_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifact',
            name='file_type',
            field=models.CharField(choices=[('PDF', 'PDF'), ('CSV', 'CSV'), ('XLSX', 'XLSX')], max_length=20),
        ),
    ]
