# Generated by Django 6.0.6 on 2026-06-28 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0003_alter_artifact_file_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifact',
            name='file_type',
            field=models.CharField(choices=[('IMAGE', 'Image'), ('TEXT', 'Text'), ('PDF', 'PDF'), ('CSV', 'CSV'), ('XLSX', 'XLSX')], max_length=20),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='status',
            field=models.CharField(choices=[('UPLOADED', 'Uploaded'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='UPLOADED', max_length=20),
        ),
    ]
