# Generated by Django 6.0.6 on 2026-06-23 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialevent',
            name='merchant',
            field=models.CharField(db_index=True, default='UNKNOWN', max_length=255),
        ),
    ]
