# Generated by Django 6.0.6 on 2026-06-28 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_events', '0002_financialevent_merchant'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialevent',
            name='category',
            field=models.CharField(choices=[('FOOD', 'Food'), ('SHOPPING', 'Shopping'), ('TRAVEL', 'Travel'), ('BILLS', 'Bills'), ('HEALTH', 'Health'), ('ENTERTAINMENT', 'Entertainment'), ('TRANSFER', 'Transfer'), ('INCOME', 'Income'), ('OTHER', 'Other')], default='OTHER', max_length=30),
        ),
    ]
